#!/usr/bin/env nextflow
nextflow.enable.dsl = 2


include {
    glNexus_jointCall;
    sawFish2_jointCall_caseID;
    svdb_sawFish2_jointCall_caseID;
    exo14_2508_exome;
    exo14_2508_genome;
    exo14_2508_SV
} from "../modules/dnaModules.nf"


workflow FAMILY_ANALYSIS {

    take:
    glnexus_manifest_ch
    sawfish_manifest_ch
    hpo_ch
    ss_ch

    main:

    glNexus_jointCall(glnexus_manifest_ch)

    sawFish2_jointCall_caseID(sawfish_manifest_ch)

    svdb_sawFish2_jointCall_caseID(
        sawFish2_jointCall_caseID.out.sv_jointCall_caseID_vcf
    )


    /*
     * Exomiser / Genomiser
     *
     * Only run when --hpo has been supplied.
     */
    if (params.hpo) {

        glNexus_jointCall.out.glnexus_wes_roi_vcf
            .combine(hpo_ch)
            .combine(ss_ch)
            | exo14_2508_exome


        glNexus_jointCall.out.glnexus_vcf
            .combine(hpo_ch)
            .combine(ss_ch)
            | exo14_2508_genome


        svdb_sawFish2_jointCall_caseID.out.sawfish_caseID_AF10
            .combine(hpo_ch)
            .combine(ss_ch)
            | exo14_2508_SV
    }
}


workflow FAMILY_ANALYSIS_ENTRY {

    /*
     * Read family JSON generated by pacbio.familyAnalysis helper.
     */
    def familyData = new groovy.json.JsonSlurper()
        .parse(new File(params.familyJSON))


    /*
     * Metadata used by the family-analysis processes.
     */
    def anchorMeta = [
        caseID     : familyData.caseID,
        id         : familyData.caseID,
        groupKey   : familyData.familyID,
        layoutMode : 'jointAnalysis',
        rekv       : '',
        testlist   : ''
    ]


    /*
     * Configure joint-analysis output structure.
     */
    params.outputDirTMP = params.familyDir
    params.layoutMode   = 'jointAnalysis'


    /*
     * GLnexus manifest channel.
     */
    Channel.of(
        tuple(
            anchorMeta,
            file(params.gvcfManifest, checkIfExists: true)
        )
    )
    | set { glnexus_manifest_ch }


    /*
     * Sawfish manifest channel.
     */
    Channel.of(
        tuple(
            anchorMeta,
            file(params.sawfishCSV, checkIfExists: true)
        )
    )
    | set { sawfish_manifest_ch }


    /*
     * Samplesheet channel.
     */
    Channel.fromPath(
        params.familySS,
        checkIfExists: true
    )
    | set { ss_ch }


    /*
     * HPO channel.
     *
     * Avoid:
     *
     *   def hpo_ch = params.hpo ? Channel.fromPath(...) : Channel.empty()
     *
     * because this caused:
     *
     *   Variable `Channel` already defined in the process scope
     *
     * with Nextflow 24.10.
     */
    if (params.hpo) {

        Channel.fromPath(
            params.hpo,
            checkIfExists: true
        )
        | set { hpo_ch }

    } else {

        Channel.empty()
        | set { hpo_ch }
    }


    /*
     * Run family analysis.
     */
    FAMILY_ANALYSIS(
        glnexus_manifest_ch,
        sawfish_manifest_ch,
        hpo_ch,
        ss_ch
    )
}


workflow EXOMISER_ONLY_ENTRY {

    /*
     * Re-run Exomiser/Genomiser on an already completed
     * family joint analysis.
     */

    def familyData = new groovy.json.JsonSlurper()
        .parse(new File(params.familyJSON))


    def anchorMeta = [
        caseID     : familyData.caseID,
        id         : familyData.caseID,
        groupKey   : familyData.familyID,
        layoutMode : 'jointAnalysis',
        rekv       : '',
        testlist   : ''
    ]


    params.outputDirTMP = params.familyDir
    params.layoutMode   = 'jointAnalysis'


    /*
     * Existing family jointCalls directory.
     */
    def jointCallsDir = "${familyData.jointOutdir}/jointCalls"

    def caseID = familyData.caseID
    def gv     = "hg38v4LRS"
    def rs     = "HifiReads"


    /*
     * Small-variant WES ROI VCF.
     */
    Channel.of(
        tuple(
            anchorMeta,
            file(
                "${jointCallsDir}/${caseID}.${gv}.${rs}.deepVariant.jointCall.WES_ROI.vcf.gz",
                checkIfExists: true
            ),
            file(
                "${jointCallsDir}/${caseID}.${gv}.${rs}.deepVariant.jointCall.WES_ROI.vcf.gz.tbi",
                checkIfExists: true
            )
        )
    )
    | set { wes_roi_vcf_ch }


    /*
     * Whole-genome joint VCF.
     */
    Channel.of(
        tuple(
            anchorMeta,
            file(
                "${jointCallsDir}/${caseID}.${gv}.${rs}.deepVariant.jointCall.vcf.gz",
                checkIfExists: true
            ),
            file(
                "${jointCallsDir}/${caseID}.${gv}.${rs}.deepVariant.jointCall.vcf.gz.tbi",
                checkIfExists: true
            )
        )
    )
    | set { wgs_vcf_ch }


    /*
     * Sawfish joint-call SVDB filtered VCF.
     */
    Channel.of(
        tuple(
            anchorMeta,
            file(
                "${jointCallsDir}/${caseID}.${gv}.${rs}.sawfishSV_jointCall.svdb.AF_below10pct.vcf.gz",
                checkIfExists: true
            ),
            file(
                "${jointCallsDir}/${caseID}.${gv}.${rs}.sawfishSV_jointCall.svdb.AF_below10pct.vcf.gz.tbi",
                checkIfExists: true
            )
        )
    )
    | set { sv_vcf_ch }


    /*
     * HPO is required in EXOMISER_ONLY_ENTRY.
     */
    Channel.fromPath(
        params.hpo,
        checkIfExists: true
    )
    | set { hpo_ch }


    /*
     * Family samplesheet.
     */
    Channel.fromPath(
        params.familySS,
        checkIfExists: true
    )
    | set { ss_ch }


    /*
     * Small variants.
     */
    wes_roi_vcf_ch
        .combine(hpo_ch)
        .combine(ss_ch)
        | exo14_2508_exome


    /*
     * Whole genome.
     */
    wgs_vcf_ch
        .combine(hpo_ch)
        .combine(ss_ch)
        | exo14_2508_genome


    /*
     * Structural variants.
     */
    sv_vcf_ch
        .combine(hpo_ch)
        .combine(ss_ch)
        | exo14_2508_SV
}
